config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get 'posts' => 'posts#index'
  get "posts/today" => "posts#today"
  get "posts/ranking" => "posts#ranking"
  # get "posts/indexusername" => "posts#indexusername"
  get "users/likes/:id" => "users#likes"
  resources :users
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :answers
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id # validates_uniqueness_ofによって、tweet_idとuser_id　の組が1組しかないようにバリデーションをかけました
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :answers, dependent: :destroy
    belongs_to :user
    has_many :liked_users, through: :likes, source: :user # liked_usersによって投稿が誰にいいねされているのかを簡単に取得できるようになります。
    def already_liked?(post)
        self.likes.exists?(post_id: post.id)
    end
    def self.create_all_ranks # ランキング機能のための記述！
        Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many :answers,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post #userがどの投稿をいいねしているのかを簡単に取得できるようになります
  # ユーザーが投稿に対して、すでにいいねをしているのかどうかを判定することができるようにuser.rbで、already_liked?を定義します。
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def index
    end
    
    def new
        @answer = Answer.new
        @post = Post.find_by(id: params[:post_id])
    end
    
      # Commnet /Commnets
      # Commnet /Commnets.json
    def create
        @answer = Answer.new(answer_params)
        @answer.user_id = current_user.id
        if @answer.save
            redirect_to :root
        else
            render action: :new
        end
    end
    def destroy
    end

    private
      def answer_params
        params.require(:answer).permit(:post_id,:body)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
        before_action :set_comment, only: [:show, :edit, :update, :destroy]

        # GET /Commnets/new
        def new
          @comment = Comment.new
          @post = Post.find_by(id: params[:post_id])
        end
      
        # GET /Commnets/1/edit
        def edit
        end
      
        # Commnet /Commnets
        # Commnet /Commnets.json
        def create
            @comment = Comment.new(comment_params)
            @comment.user_id = current_user.id
            if @comment.save
                redirect_to :root
            else
                render action: :new
            end
        end
      
        # PATCH/PUT /Commnets/1
        # PATCH/PUT /Commnets/1.json
        def update
        end
      
        # DELETE /Commnets/1
        # DELETE /Commnets/1.json
        def destroy
          @post=Post.find(params[:post_id])
          @comment=@post.comments.find(params[:id])
          @comment.destroy
          redirect_to post_path(@post)
        end
      
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_comment
            @comment = Comment.find(params[:id])
          end
      
          # Only allow a list of trusted parameters through.
          def comment_params
            params.require(:comment).permit(:answer,:post_id)
          end    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    def create
        @like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:today,:ranking,:show,:edit,:create,:update,:destroy,:indexusername]

  # GET /posts
  # GET /posts.json
  def index
    if params[:search] == nil
      @posts = Post.all.page(params[:page]).per(6)
    elsif params[:search] == '' 
      @posts = Post.all.page(params[:page]).per(6)
    else
      @posts = Post.where("body LIKE ? OR username LIKE ?", '%' + params[:search] + '%','%' + params[:search] + '%').page(params[:page]).per(6)
    end
    #@current_user=current_user.id
    #@ai = Post.find(params[:id])
    # @like = Like.new
    #m @post = Post.find(params[:id])
    # @post = Post.find(params[:id])
  end


  def today
    @posts = Post.order("RANDOM()").limit(1)
  end

  def ranking
    @all_ranks = Post.create_all_ranks
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
      @post = Post.find(params[:id])
      @like = Like.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id
    @post.username=current_user.name
      if @post.save
        #flash[:notice] = "#{@post.username}さん！<br>新規の問題を投稿しましたよ！"
        flash[:notice] = "問題を投稿しました"
        redirect_to :root
      else
        render action: :new
      end
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @all = @user.posts

    @likes=Like.where(user_id: @user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to :root
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/new.html.erb
<h2>解答！</h2>
<%= form_with model: @answer, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <%# 新規作成フォーム %>
      <div class="cardnewForm_title">
        <%= f.label :body %>
        <%= f.text_field :body, autofocus: true, class: "form-control", placeholder: "解答を入力" %>
      </div>
      <%# 送信ボタン %>
        <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
<% end %>
<%= link_to 'TOP', posts_path %>

app/views/comments/new.html.erb
<div class="comment-new">
  <h2 class="comment title">質問コーナー</h2>
  <%= form_with model: @comment, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%# 新規作成フォーム %>
        <div class="comment form">
          <%= f.text_area :answer, autofocus: true, class: "comment form-field", placeholder: "質問を入力" %>
        </div>
        <%# 送信ボタン %>
          <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
        </div>
  <% end %>
  <%= link_to 'TOP', posts_path,class: "comment to-top" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>GoodFunction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%# lightboxのダウンロード %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <%# lightboxのダウンロード %>

    <%# bootstrap %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%# bootstrap %>
  </head>
  <body>
    <header class="header" id="header">
      <h1><%= link_to "みんガメ",root_path, class: "nav-link" %></h1>
      <div>
        <ul class="header-listarea">
          <% if user_signed_in? %>
            <li>ようこそ！<span class="font-weight-bold"><%= current_user.name %></span>さん</li>
            <li><%= link_to "サインアウト",destroy_user_session_path, class: "nav-link",method: :delete %></li>
            <li><%= link_to "退会する",user_path(current_user.id), class: "nav-link",method: :delete %></li>
          <% else %>
            <li><%= link_to "サインイン",new_user_session_path, class: "nav-link" %></li>
            <li><%= link_to "新規登録",new_user_registration_path, class: "nav-link" %></li>
          <% end %>
          <li><%= link_to '新規問題の作成', new_post_path,class: "nav-link" %></li>
          <li><%= link_to '今日の一問', posts_today_path,class: "nav-link" %></li>
          <li><%= link_to '良問ランキング', posts_ranking_path,class: "nav-link" %></li>
        </ul>
      </div>
    </header>
    <%= javascript_pack_tag 'layouts/application' %>
    <div class="contentarea">
      <div class="trigger" id="trigger"></div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if flash[:notice] %>
  <p class="flash post-new-post"><i class="far fa-paper-plane"></i><%= flash[:notice].html_safe %></p>
<% end %>

<h1 class="index-title">ウミガメのスープ問題集</h1>
<div class="search-area">
  <%= form_tag({controller:"posts",action:"index"}, method: :get,class: "search-form") do %>
    <%= text_field_tag :search,'' ,placeholder: "気になる単語を入力して検索" %>
    <%= button_tag :type => "submit", :class =>"search-btn" do %>
      <i class="fa fa-search"></i>
    <% end %>
  <% end %>
</div>

<div class="index-questionarea">
  <% @posts.each do |post| %>
    <div class="index-question">
      <p class="proposer">
        <%= link_to(user_path(post.id)) do %>
          <%= post.username %>さんからの投稿
        <% end %>
        <%#= link_to post.username+'さんからの投稿', user_path(post.id) %>
      </p>
      <p class="question-content"><%= post.body %></p>
      <%# ここをshow.html.erbに記述したらいける %>
      <div class="good_answerlink">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(post) %>
          <p><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_like_path(id: post.id, post_id: post.id),method: :delete) %><%= post.liked_users.count %></p>
        <% else %>
          <p class="goodbtn"><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_likes_path(id: post.id, post_id: post.id),method: :post) %><%= post.liked_users.count %></p>　　<%# <%= link_to 'いいね', post_likes_path(post),method: :post %>
        <% end %>
        <% if post.user_id == current_user.id %>
          <p class="answerlink"><%= link_to '解答作成', new_post_answer_path(post) %></p>
        <% end %>
      <% end %>
      </div>
      <div class="index_icon_area">
        <p><%= link_to(content_tag(:i, '詳細へ', class: 'fas fa-angle-double-right'), post_path(post)) %></p>
        <% if user_signed_in? %> <%# ユーザーがサインインしていれば %>
          <% if post.user_id == current_user.id %>　<%# 投稿のuser_idとログインユーザーのIDが一致していれば %>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(post)) %></p>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(post), :method => :delete) %></p>
          <% end %>
        <% end %>
        <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(post)) %></p>
      </div>
      <%# ここをshow.html.erbに記述したらいける %>
    </div>
  <% end %>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'TOP', posts_path %>

app/views/posts/ranking.html.erb
<h1 class="index-title ranking">良問ランキング</h1>
<div class="index-questionarea">
  <% @all_ranks.each.with_index(1) do |post,i| %>
    <div class="index-question">
      <p class="proposer">第<%= i %>位<br><%= post.username %>さんからの問題</p>
      <p class="question-content"><%= post.body %></p>
      <%# ここをshow.html.erbに記述したらいける %>
      <div class="good_answerlink">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(post) %>
          <p><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_like_path(id: post.id, post_id: post.id),method: :delete) %><%= post.liked_users.count %></p>
        <% else %>
          <p class="goodbtn"><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_likes_path(id: post.id, post_id: post.id),method: :post) %><%= post.liked_users.count %></p>　　<%# <%= link_to 'いいね', post_likes_path(post),method: :post %>
        <% end %>
        <% if post.user_id == current_user.id %>
          <p class="answerlink"><%= link_to '解答作成', new_post_answer_path(post) %></p>
        <% end %>
      <% end %>
      </div>
      <div class="index_icon_area">
        <p><%= link_to(content_tag(:i, '詳細へ', class: 'fas fa-angle-double-right'), post_path(post)) %></p>
        <% if user_signed_in? %> <%# ユーザーがサインインしていれば %>
          <% if post.user_id == current_user.id %>　<%# 投稿のuser_idとログインユーザーのIDが一致していれば %>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(post)) %></p>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(post), :method => :delete) %></p>
          <% end %>
        <% end %>
        <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(post)) %></p>
      </div>
      <%# ここをshow.html.erbに記述したらいける %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
  <p id="notice"><%= notice %></p>
  <div class="index-question show">
    <p class="proposer"><%= @post.username %>さんからの問題</p>
    <p class="question-content"><%= @post.body %></p>
  </div>
  <div class="show-content-area">
    <h1 class="show good-count">いいね件数: <%= @post.likes.count %></h1>
    <%#<% if user_signed_in? %>
    <%#  <% if current_user.already_liked?(@post) %>
    <%#    <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
    <%#  <% else %>
    <%#    <%= button_to 'いいね', post_likes_path(@post) %>
    <%#  <% end %>
    <%#<% end %>
    <h1 class="show good-user">いいねしたユーザー</h1>
    <% @post.liked_users.each do |user| %>
      <p class="show good-username"><%= user.name %></p>
    <% end %>

    <%# # 投稿したコメントを表示★★★★★★★★★★★★★★★★★★ %>
    <% @post.comments.each do |comment| %>
      <p class="show comment"><%= comment.answer %><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt show'), post_comment_path(@post,comment), :method => :delete) %></p>
    <% end %>

    <% @post.answers.each do |answer| %>
      <p class="show answer"><%= answer.body %></p>
    <% end %>
    <%# ここまで %>


    <%= link_to '質問する', new_post_comment_path(@post),class: "show to-post-comment" %> |
    <%= link_to 'Edit', edit_post_path(@post),class: "show to-post-edit" %> |
    <%= link_to 'TOP', posts_path,class: "show to-top" %>
  </div>
</div>

app/views/posts/today.html.erb
<% @posts.each do |post| %>
    <h1 class="today-title">今日の一問</h1>
    <div class="index-question today">
      <p class="proposer"><%= post.username %>さんからの問題</p>
      <p class="question-content"><%= post.body %></p>
      <div class="index_icon_area">
        <p><%= link_to(content_tag(:i, '', class: 'fas fa-angle-double-right'), post_path(post)) %></p>
        <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(post)) %></p>
        <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(post), :method => :delete) %></p>
        <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(post)) %></p>
      </div>
      <%# ここをshow.html.erbに記述したらいける %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1 class="users_show"><%= @user.name %>さんの投稿一覧</h1>
<div class="index-questionarea">
    <% @all.each do |a| %>
        <div class="index-question">
            <p class="question-content"><%= a.body %></p>
            <div class="index_icon_area">
                <p><%= link_to(content_tag(:i, '詳細へ', class: 'fas fa-angle-double-right'), post_path(a)) %></p>
                <% if user_signed_in? %> <%# ユーザーがサインインしていれば %>
                <% if a.user_id == current_user.id %>　<%# 投稿のuser_idとログインユーザーのIDが一致していれば %>
                    <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(a)) %></p>
                    <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(a), :method => :delete) %></p>
                <% end %>
                <% end %>
                <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(a)) %></p>
            </div>
        </div>
    <% end %>
</div>
<h1 class="users_show"><%= @user.name %>さんのいいねした投稿一覧</h1>
<div class="index-questionarea">
    <% @likes.each do |l| %>
        <div class="index-question">
            <p class="question-content"><%= post=Post.find(l.post_id).body %><% l.post_id %></p>
            <div class="index_icon_area">
                <p><%= link_to(content_tag(:i, '詳細へ', class: 'fas fa-angle-double-right'), post_path(l)) %></p>
                <% if user_signed_in? %> <%# ユーザーがサインインしていれば %>
                <% if l.user_id == current_user.id %>　<%# 投稿のuser_idとログインユーザーのIDが一致していれば %>
                    <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(l)) %></p>
                    <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(l), :method => :delete) %></p>
                <% end %>
                <% end %>
                <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(l)) %></p>
            </div>
        </div>
    <% end %>
</div>